### PR TITLE
Adding http-server as a way to run a local dev server without requiring firebase creds

### PR DESCRIPTION
**Pull request by barryels**
#2

### CODE REVIEW

**Comment by sebastiansandqvist** [comment]
I prefer to use `firebase-tools` for to run the server, not `http-server`, so that the settings in `firebase.json` do not need to be replicated and in order to ensure that the local version of the site is the same as the live version.

In other words, I think the `dev` script could just be: `npm run start & npm run watch`

**Comment by barryels** [comment]
@sebastiansandqvist, yup, I completely agree :)
It's just that firebase (when running `firebase serve...` is trying to connect to your remote project before starting up a local server, but it's using my firebase credentials to attempt to login to your project, which it obviously won't allow. This then bombs out and I can't get it to serve the local files :/

Debug log below:

```
$ npm start

> mithril-examples@1.0.0 start ~/Projects/mithril-examples
> firebase serve --port 3000


Error: HTTP Error: 401, The entered credentials were incorrect.

npm ERR! Linux 4.8.0-46-generic
npm ERR! argv "~/.linuxbrew/Cellar/node/7.9.0/bin/node" "~/.linuxbrew/bin/npm" "start"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mithril-examples@1.0.0 start: `firebase serve --port 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mithril-examples@1.0.0 start script 'firebase serve --port 3000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mithril-examples package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     firebase serve --port 3000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mithril-examples
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mithril-examples
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/.npm/_logs/2017-04-28T19_18_00_890Z-debug.log
```

**Comment by sebastiansandqvist** [comment]
I didn't realize they would check credentials just to run locally. I think firebase serve is just a wrapper around superstatic so I will look into using superstatic instead.

**Comment by sebastiansandqvist** [comment]
I've got superstatic working with the existing firebase config, so it should be possible to run the server locally now without firebase requiring a login (although I haven't tested it while logged out yet, so if the problem persists we can re-open this).

**Pull request closed without merging**
